import {
  IconActivity,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsSort,
  IconArrowUp,
  IconBook,
  IconBrain,
  IconBulb,
  IconCalendar,
  IconCalendarPlus,
  IconCamera,
  IconCategory,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsLeft,
  IconChevronsRight,
  IconChevronUp,
  IconCircleCheck,
  IconClipboardList,
  IconClock,
  IconColumns,
  IconCopyCheck,
  IconCpu,
  IconDatabase,
  IconDeviceFloppy,
  IconDots,
  IconDownload,
  IconEdit,
  IconEye,
  IconFile,
  IconFileAnalytics,
  IconFileText,
  IconFileZip,
  IconFolder,
  IconHelp,
  IconInfoCircle,
  IconLanguage,
  IconLayoutDashboard,
  IconLayoutDistributeVertical,
  IconLayoutGrid,
  IconLayoutList,
  IconLayoutRows,
  IconLicense,
  IconLink,
  IconLoader,
  IconLock,
  IconLogout,
  IconMail,
  IconMap,
  IconMoonStars,
  IconPalette,
  IconPencil,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconPolygon,
  IconRefresh,
  IconRocket,
  IconRoute,
  IconSearch,
  IconSelector,
  IconSettings,
  IconShield,
  IconSquare,
  IconStar,
  IconStarFilled,
  IconSun,
  IconTable,
  IconTag,
  IconTarget,
  IconTerminal,
  IconTrain,
  IconTrash,
  IconTrendingUp,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserCircle,
  IconUserOff,
  IconUsers,
  IconVectorBezier2,
  IconVideo,
  IconWifi,
  IconX,
} from "@tabler/icons-react";

export const RawIcons = {
  AdjustmentsHorizontal: IconAdjustmentsHorizontal,
  AlertCircle: IconAlertCircle,
  AlertTriangle: IconAlertTriangle,
  ArrowDown: IconArrowDown,
  ArrowLeft: IconArrowLeft,
  ArrowRight: IconArrowRight,
  ArrowUp: IconArrowUp,
  Book: IconBook,
  Brain: IconBrain,
  CalendarPlus: IconCalendarPlus,
  Camera: IconCamera,
  Category: IconCategory,
  ChartBar: IconChartBar,
  Check: IconCheck,
  CheckCircle: IconCircleCheck,
  ChevronDown: IconChevronDown,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  ChevronUp: IconChevronUp,
  ChevronsLeft: IconChevronsLeft,
  ChevronsRight: IconChevronsRight,
  Activity: IconActivity,
  ClipboardList: IconClipboardList,
  Calendar: IconCalendar,
  Clock: IconClock,
  Bulb: IconBulb,
  Columns: IconColumns,
  CopyCheck: IconCopyCheck,
  Cpu: IconCpu,
  Dashboard: IconLayoutDashboard,
  Database: IconDatabase,
  Dots: IconDots,
  Download: IconDownload,
  Edit: IconEdit,
  Eye: IconEye,
  File: IconFile,
  FileAnalytics: IconFileAnalytics,
  FileText: IconFileText,
  FileZip: IconFileZip,
  DeviceFloppy: IconDeviceFloppy,
  Folder: IconFolder,
  HelpCircle: IconHelp,
  InfoCircle: IconInfoCircle,
  Language: IconLanguage,
  LayoutDistributeVertical: IconLayoutDistributeVertical,
  LayoutGrid: IconLayoutGrid,
  LayoutList: IconLayoutList,
  LayoutRows: IconLayoutRows,
  License: IconLicense,
  Link: IconLink,
  Loader: IconLoader,
  Lock: IconLock,
  Logout: IconLogout,
  Mail: IconMail,
  Map: IconMap,
  Model: IconBrain,
  Moon: IconMoonStars,
  Palette: IconPalette,
  Pause: IconPlayerPause,
  Pencil: IconPencil,
  Play: IconPlayerPlay,
  PlayerPause: IconPlayerPause,
  PlayerPlay: IconPlayerPlay,
  PlayerStop: IconPlayerStop,
  Plus: IconPlus,
  Polygon: IconPolygon,
  Recipe: IconBook,
  Refresh: IconRefresh,
  Rocket: IconRocket,
  Route: IconRoute,
  Search: IconSearch,
  Selector: IconSelector,
  Settings: IconSettings,
  Shield: IconShield,
  Sort: IconArrowsSort,
  Square: IconSquare,
  Star: IconStar,
  StarFilled: IconStarFilled,
  Sun: IconSun,
  Table: IconTable,
  Tag: IconTag,
  Target: IconTarget,
  Task: IconClipboardList,
  Terminal: IconTerminal,
  Train: IconTrain,
  Trash: IconTrash,
  TrendingUp: IconTrendingUp,
  Upload: IconUpload,
  User: IconUser,
  UserCheck: IconUserCheck,
  UserCircle: IconUserCircle,
  UserOff: IconUserOff,
  Users: IconUsers,
  VectorBezier2: IconVectorBezier2,
  Video: IconVideo,
  Wifi: IconWifi,
  X: IconX,
};
