import {
  IconArrowDown,
  IconArrowUp,
  IconArrowsSort,
  IconBook,
  IconBrain,
  IconCheck,
  IconClipboardList,
  IconCopyCheck,
  IconDownload,
  IconDots,
  IconEye,
  IconFileAnalytics,
  IconInfoCircle,
  IconLanguage,
  IconLayoutGrid,
  IconLayoutList,
  IconLicense,
  IconLogout,
  IconMoonStars,
  IconPencil,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSun,
  IconTable,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconVideo,
  IconX,
} from "@tabler/icons-react";

export const RawIcons = {
  ArrowDown: IconArrowDown,
  ArrowUp: IconArrowUp,
  Check: IconCheck,
  ClipboardList: IconClipboardList,
  CopyCheck: IconCopyCheck,
  Download: IconDownload,
  Dots: IconDots,
  Eye: IconEye,
  FileAnalytics: IconFileAnalytics,
  InfoCircle: IconInfoCircle,
  Language: IconLanguage,
  LayoutGrid: IconLayoutGrid,
  LayoutList: IconLayoutList,
  License: IconLicense,
  Logout: IconLogout,
  Model: IconBrain,
  Moon: IconMoonStars,
  Pencil: IconPencil,
  PlayerPlay: IconPlayerPlay,
  PlayerStop: IconPlayerStop,
  Plus: IconPlus,
  Recipe: IconBook,
  Refresh: IconRefresh,
  Search: IconSearch,
  Sort: IconArrowsSort,
  Sun: IconSun,
  Table: IconTable,
  Task: IconClipboardList,
  Trash: IconTrash,
  Upload: IconUpload,
  User: IconUser,
  Users: IconUsers,
  Video: IconVideo,
  X: IconX,
};
