import {
  IconArrowDown,
  IconArrowUp,
  IconArrowsSort,
  IconBook,
  IconBrain,
  IconCheck,
  IconChartBar,
  IconChevronLeft,
  IconChevronRight,
  IconChevronDown,
  IconChevronUp,
  IconChevronsLeft,
  IconChevronsRight,
  IconSelector,
  IconClipboardList,
  IconCopyCheck,
  IconCpu,
  IconDatabase,
  IconDownload,
  IconDots,
  IconEye,
  IconFileAnalytics,
  IconFileZip,
  IconInfoCircle,
  IconLanguage,
  IconLayoutGrid,
  IconLayoutList,
  IconLicense,
  IconLogout,
  IconMoonStars,
  IconPencil,
  IconEdit,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSun,
  IconTable,
  IconTrain,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconVideo,
  IconX,
  IconPolygon,
  IconArrowRight,
  IconArrowLeft,
  IconAlertCircle,
  IconTag,
  IconSettings,
  IconCamera,
  IconSquare,
  IconFolder,
  IconTarget,
  IconLoader,
  IconClock,
  IconVectorBezier2,
  IconRoute,
  IconLink,
  IconAlertTriangle,
  IconUserOff,
  IconUserCheck,
  IconMail,
  IconLock,
  IconUserCircle,
  IconRocket,
  IconActivity,
  IconCalendar,
  IconMap,
  IconBulb,
  IconTrendingUp,
  IconStar,
  IconStarFilled,
  IconFile,
  IconFileText,
  IconShield,
  IconPalette,
} from "@tabler/icons-react";

export const RawIcons = {
  ArrowDown: IconArrowDown,
  ArrowUp: IconArrowUp,
  ArrowLeft: IconArrowLeft,
  ArrowRight: IconArrowRight,
  AlertCircle: IconAlertCircle,
  AlertTriangle: IconAlertTriangle,
  Brain: IconBrain,
  Book: IconBook,
  Camera: IconCamera,
  ChartBar: IconChartBar,
  Check: IconCheck,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  ChevronDown: IconChevronDown,
  ChevronUp: IconChevronUp,
  ChevronsLeft: IconChevronsLeft,
  ChevronsRight: IconChevronsRight,
  Selector: IconSelector,
  ClipboardList: IconClipboardList,
  Clock: IconClock,
  CopyCheck: IconCopyCheck,
  Cpu: IconCpu,
  Database: IconDatabase,
  Download: IconDownload,
  Dots: IconDots,
  Eye: IconEye,
  Edit: IconEdit,
  FileAnalytics: IconFileAnalytics,
  FileZip: IconFileZip,
  InfoCircle: IconInfoCircle,
  Language: IconLanguage,
  LayoutGrid: IconLayoutGrid,
  LayoutList: IconLayoutList,
  License: IconLicense,
  Link: IconLink,
  Lock: IconLock,
  Logout: IconLogout,
  Mail: IconMail,
  Model: IconBrain,
  Moon: IconMoonStars,
  Pencil: IconPencil,
  PlayerPlay: IconPlayerPlay,
  PlayerStop: IconPlayerStop,
  Plus: IconPlus,
  Polygon: IconPolygon,
  Recipe: IconBook,
  Refresh: IconRefresh,
  Route: IconRoute,
  Search: IconSearch,
  Settings: IconSettings,
  Sort: IconArrowsSort,
  Square: IconSquare,
  Sun: IconSun,
  Table: IconTable,
  Tag: IconTag,
  Task: IconClipboardList,
  Train: IconTrain,
  Trash: IconTrash,
  Upload: IconUpload,
  User: IconUser,
  Users: IconUsers,
  UserOff: IconUserOff,
  UserCheck: IconUserCheck,
  UserCircle: IconUserCircle,
  VectorBezier2: IconVectorBezier2,
  Video: IconVideo,
  X: IconX,
  Folder: IconFolder,
  Target: IconTarget,
  Loader: IconLoader,
  Rocket: IconRocket,
  Activity: IconActivity,
  Calendar: IconCalendar,
  Map: IconMap,
  Bulb: IconBulb,
  TrendingUp: IconTrendingUp,
  Star: IconStar,
  StarFilled: IconStarFilled,
  File: IconFile,
  FileText: IconFileText,
  Play: IconPlayerPlay,
  Shield: IconShield,
  Palette: IconPalette,
};
